##
#  BASE STAGE
##
FROM node:16.16.0-alpine3.16 as base
WORKDIR /app


##
# DEPENEDENCY STAGE
##
FROM base as dependencies
COPY package.json package-lock.json ./
RUN npm ci

##
# DEV STAGE
##
FROM dependencies as dev
COPY . .
CMD [ "npm" , "run" , "start" ]

##
# BUILD STAGE
##
FROM dependencies as build
COPY . .
COPY --from=dependencies /app/node_modules/ ./node_modules
RUN npm run build:production

##
# PROD STAGE
##
FROM nginx:1.22.1-alpine as prod
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/build .

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]